server:
  port: 8765

spring:
  application:
    name: zuul-gateway

zuul:
  ignoredHeaders: Access-Control-Allow-Credentials, Access-Control-Allow-Origin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
