server:
  port: 8765

spring:
  application:
    name: zuul-gateway

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka:
  client:
    service-url:
      defaultZone: http://${IP_Address}:8761/eureka/
