server:
  port: 8761

spring:
  application:
    name: product-availability-eureka

eureka:
#  instance:
#    prefer-ip-address: true
#    ip-address: 172.17.0.1
  client:
    register-with-eureka: false
    fetch-registry: false